project:
  type: website
  output-dir: docs
  preview: 
    port: 3000

website:
  title: "opensource-analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



